version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: "on-failure"
    ports:
      - 5432:5432
    # volumes:
      # - ./postgredb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8

  nginx:
    container_name: nginx
    build: ./nginx
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./IsmayilliDovletHumanitarVeTexnologiyaKolleci/media:/app/media
      - ./IsmayilliDovletHumanitarVeTexnologiyaKolleci/staticfiles:/app/static

  app:
    container_name: app
    build: .
    restart: "on-failure"
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/src/app
    env_file: .env
    depends_on:
      - postgres
