version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: "on-failure"
    ports:
      - 5432:5432
    # volumes:
    # - ./postgredb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8

  web:
    container_name: kollec
    build: .
    restart: "always"
    env_file: .env
    environment:
 #     - VIRTUAL_HOST=
      - VIRTUAL_PORT=80
      - TIMEOUT=300
      - HTTP_PORT=80
      - STATS_PORT=8046
    command: >
      sh -c "/venv/bin/python manage.py makemigrations &&
             /venv/bin/python manage.py migrate &&
             /venv/bin/python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/kollec
    ports:
      - "80:80"
    links:
      - postgres
    depends_on:
      - "postgres"

networks:
  default:
    external:
      name: nginx-proxy