# Generated by Django 3.2.8 on 2022-01-09 21:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slogan', models.CharField(max_length=100, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description')),
                ('active_student_number', models.IntegerField()),
                ('faculty_number', models.IntegerField()),
                ('graduate_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'MainPage',
                'verbose_name_plural': 'MainPage',
            },
        ),
        migrations.AlterField(
            model_name='mostquestions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mostquestions',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='mostquestions',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='mostquestions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
