# Generated by Django 3.2.8 on 2022-01-23 12:31

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostquestions',
            name='description_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Cavab'),
        ),
        migrations.AddField(
            model_name='mostquestions',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Cavab'),
        ),
        migrations.AddField(
            model_name='mostquestions',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Cavab'),
        ),
        migrations.AddField(
            model_name='mostquestions',
            name='title_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Sual'),
        ),
        migrations.AddField(
            model_name='mostquestions',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Sual'),
        ),
        migrations.AddField(
            model_name='mostquestions',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Sual'),
        ),
        migrations.AlterField(
            model_name='mostquestions',
            name='description',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='Cavab'),
            preserve_default=False,
        ),
    ]
