# Generated by Django 3.2.8 on 2022-01-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220123_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostquestions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mostquestions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
