# Generated by Django 3.2.8 on 2021-12-23 23:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('question', models.CharField(max_length=50, verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Library FAQ',
                'verbose_name_plural': 'Library FAQs',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_az', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Fənn',
                'verbose_name_plural': 'Fənnlər',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('full_name', models.CharField(default='', max_length=50, verbose_name='Full Name')),
                ('full_name_en', models.CharField(default='', max_length=50, null=True, verbose_name='Full Name')),
                ('full_name_az', models.CharField(default='', max_length=50, null=True, verbose_name='Full Name')),
                ('full_name_ru', models.CharField(default='', max_length=50, null=True, verbose_name='Full Name')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('photo', models.ImageField(default='teachers/default.png', upload_to='teachers', verbose_name='Photo')),
                ('subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='staff.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Müəllim',
                'verbose_name_plural': 'Müəllimlər',
            },
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='Max 50 char.', max_length=50, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Max 50 char.', max_length=50, null=True, verbose_name='Title')),
                ('title_az', models.CharField(help_text='Max 50 char.', max_length=50, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Max 50 char.', max_length=50, null=True, verbose_name='Title')),
                ('file', models.FileField(default=None, upload_to='pdf/', verbose_name='File')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_category', to='staff.subject', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'PDF',
                'verbose_name_plural': 'PDFs',
            },
        ),
    ]
