# Generated by Django 3.2.8 on 2022-03-08 09:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_az', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('description_az', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='DeputyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_az', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Deputy Category',
                'verbose_name_plural': 'Deputy Categories',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(default='', max_length=50, verbose_name='Full Name')),
                ('full_name_en', models.CharField(default='', max_length=50, null=True, verbose_name='Full Name')),
                ('full_name_az', models.CharField(default='', max_length=50, null=True, verbose_name='Full Name')),
                ('full_name_ru', models.CharField(default='', max_length=50, null=True, verbose_name='Full Name')),
                ('image', models.ImageField(default=None, upload_to='director/', verbose_name='Image')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('email', models.EmailField(default='', max_length=50, verbose_name='Email')),
                ('start_date', models.DateField(default=None, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Max 50 char.', max_length=50, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Max 50 char.', max_length=50, null=True, verbose_name='Title')),
                ('title_az', models.CharField(help_text='Max 50 char.', max_length=50, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Max 50 char.', max_length=50, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('description_az', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Libraries',
            },
        ),
        migrations.CreateModel(
            name='LibraryFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=50, verbose_name='Question')),
                ('question_en', models.CharField(max_length=50, null=True, verbose_name='Question')),
                ('question_az', models.CharField(max_length=50, null=True, verbose_name='Question')),
                ('question_ru', models.CharField(max_length=50, null=True, verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Answer')),
                ('answer_en', ckeditor.fields.RichTextField(null=True, verbose_name='Answer')),
                ('answer_az', ckeditor.fields.RichTextField(null=True, verbose_name='Answer')),
                ('answer_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Library FAQ',
                'verbose_name_plural': 'Library FAQs',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_az', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Fənn',
                'verbose_name_plural': 'Fənnlər',
            },
        ),
        migrations.CreateModel(
            name='TeacherTextColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Teacher text color',
                'verbose_name_plural': 'Teacher text colors',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(default='', max_length=50, verbose_name='Full Name')),
                ('full_name_en', models.CharField(default='', max_length=50, null=True, verbose_name='Full Name')),
                ('full_name_az', models.CharField(default='', max_length=50, null=True, verbose_name='Full Name')),
                ('full_name_ru', models.CharField(default='', max_length=50, null=True, verbose_name='Full Name')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('photo', models.ImageField(default='teachers/default.png', upload_to='teachers', verbose_name='Photo')),
                ('subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='staff.subject', verbose_name='Subject')),
                ('text_color', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_text_color', to='staff.teachertextcolor', verbose_name='Text color')),
            ],
            options={
                'verbose_name': 'Müəllim',
                'verbose_name_plural': 'Müəllimlər',
            },
        ),
        migrations.CreateModel(
            name='ReceptionDaysOfDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField(default=None, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(default=None, null=True, verbose_name='End Time')),
                ('director', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='director_days', to='staff.director', verbose_name='Director')),
            ],
            options={
                'verbose_name': 'Reception Days Of Director',
                'verbose_name_plural': 'Reception Days Of Directors',
            },
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Max 50 char.', max_length=50, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Max 50 char.', max_length=50, null=True, verbose_name='Title')),
                ('title_az', models.CharField(help_text='Max 50 char.', max_length=50, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Max 50 char.', max_length=50, null=True, verbose_name='Title')),
                ('file', models.FileField(default=None, upload_to='pdf/', verbose_name='File')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_category', to='staff.subject', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'PDF',
                'verbose_name_plural': 'PDFs',
            },
        ),
        migrations.CreateModel(
            name='HeadOfDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(default='', max_length=70, verbose_name='Full Name')),
                ('full_name_en', models.CharField(default='', max_length=70, null=True, verbose_name='Full Name')),
                ('full_name_az', models.CharField(default='', max_length=70, null=True, verbose_name='Full Name')),
                ('full_name_ru', models.CharField(default='', max_length=70, null=True, verbose_name='Full Name')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='Phone')),
                ('image', models.ImageField(default=None, upload_to='department/', verbose_name='Image')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='head_of_department', to='staff.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Head Of Department',
                'verbose_name_plural': 'Head Of Departments',
            },
        ),
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(default='', max_length=50, verbose_name='Full Name')),
                ('full_name_en', models.CharField(default='', max_length=50, null=True, verbose_name='Full Name')),
                ('full_name_az', models.CharField(default='', max_length=50, null=True, verbose_name='Full Name')),
                ('full_name_ru', models.CharField(default='', max_length=50, null=True, verbose_name='Full Name')),
                ('image', models.ImageField(default=None, upload_to='deputy/', verbose_name='Image')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='Phone')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='deputy_category', to='staff.deputycategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Deputy',
                'verbose_name_plural': 'Deputies',
            },
        ),
    ]
