# Generated by Django 3.2.8 on 2022-01-23 12:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryfaq',
            name='answer_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='libraryfaq',
            name='answer_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='libraryfaq',
            name='answer_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='libraryfaq',
            name='question_az',
            field=models.CharField(max_length=50, null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='libraryfaq',
            name='question_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='libraryfaq',
            name='question_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Question'),
        ),
    ]
