# Generated by Django 3.2.8 on 2021-12-14 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdf',
            options={'verbose_name': 'PDF', 'verbose_name_plural': 'PDFs'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Müəllim', 'verbose_name_plural': 'Müəllimlər'},
        ),
        migrations.AlterField(
            model_name='pdf',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_category', to='staff.subject', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(default=None, upload_to='pdf/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title_az',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='teachers/default.png', upload_to='teachers', verbose_name='Photo'),
        ),
    ]
