# Generated by Django 3.2.8 on 2021-12-23 22:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20211214_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('question', models.CharField(max_length=50, verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Library FAQ',
                'verbose_name_plural': 'Library FAQs',
            },
        ),
    ]
