# Generated by Django 3.2.8 on 2021-12-23 23:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(default=None, upload_to='about/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Haqqımızda',
                'verbose_name_plural': 'Haqqımızda',
            },
        ),
        migrations.CreateModel(
            name='Admissionrules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('total_rules', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('from_9_rules', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('from_11_rules', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'qəbul qaydaları',
                'verbose_name_plural': 'qəbul qaydaları',
            },
        ),
        migrations.CreateModel(
            name='CareerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'karyera dəstəyi',
                'verbose_name_plural': 'karyera dəstəyi',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='Max 100 char.', max_length=100, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title')),
                ('title_az', models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Dateofcreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Yaradilma tarixi',
                'verbose_name_plural': 'Yaradilma tarixi',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='Max 100 char.', max_length=100, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title')),
                ('title_az', models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(default=None, upload_to='faculty/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'FBK',
                'verbose_name_plural': 'FBKlar',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(help_text='Max 100 char.', max_length=100, verbose_name='Title')),
                ('image', models.ImageField(default=None, upload_to='gallery/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Practic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='Max 100 char.', max_length=100, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('image_icon', models.ImageField(default=None, upload_to='practic/', verbose_name='Image icon')),
                ('image', models.ImageField(default=None, upload_to='practic/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Practic',
                'verbose_name_plural': 'Practies',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Abunəçi',
                'verbose_name_plural': 'Abunəçilər',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='Max 100 char.', max_length=100, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title')),
                ('title_az', models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('image_icon', models.ImageField(default=None, upload_to='specialty/', verbose_name='Image')),
                ('faculty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='specialty_faculty', to='about.faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Ixtisas',
                'verbose_name_plural': 'Ixtisaslar',
            },
        ),
        migrations.CreateModel(
            name='PracticPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='Max 100 char.', max_length=100, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('practic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='practic_place', to='about.practic', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'PracticPlace',
                'verbose_name_plural': 'PracticPlaces',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='Max 100 char.', max_length=100, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title')),
                ('title_az', models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(default=None, upload_to='news/', verbose_name='Image')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='news_category', to='about.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Xəbər',
                'verbose_name_plural': 'Xəbərlər',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='Max 100 char.', max_length=100, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title')),
                ('title_az', models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('description_az', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(default=None, upload_to='event/', verbose_name='Image')),
                ('date', models.DateTimeField(verbose_name='DateTime')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_category', to='about.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
