# Generated by Django 3.2.8 on 2022-01-07 20:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionrules',
            name='from_11_rules',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='From 11 Admission'),
        ),
        migrations.AlterField(
            model_name='admissionrules',
            name='from_9_rules',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='From 9 Admission'),
        ),
        migrations.AlterField(
            model_name='admissionrules',
            name='total_rules',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='General Admission'),
        ),
    ]
