# Generated by Django 3.2.8 on 2021-10-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_title_new_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsimage',
            old_name='image',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='newsimage',
            name='news',
        ),
        migrations.AddField(
            model_name='new',
            name='img',
            field=models.ManyToManyField(related_name='image', to='about.NewsImage'),
        ),
    ]
