# Generated by Django 3.2.8 on 2022-01-08 23:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='description_az',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_az',
            field=models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_en',
            field=models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_ru',
            field=models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='Title'),
        ),
    ]
