# Generated by Django 3.2.8 on 2021-11-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20211031_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='img',
        ),
        migrations.AddField(
            model_name='new',
            name='images',
            field=models.ManyToManyField(related_name='news', to='about.NewsImage'),
        ),
    ]
