# Generated by Django 3.2.8 on 2022-01-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20220108_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(help_text='Max 100 char.', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name_az',
            field=models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name_en',
            field=models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name_ru',
            field=models.CharField(help_text='Max 100 char.', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='status',
            field=models.CharField(help_text='Max 100 char.', max_length=100, verbose_name='status'),
        ),
    ]
