# Generated by Django 3.2.8 on 2021-11-01 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20211101_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='images',
            new_name='img',
        ),
    ]
