# Generated by Django 3.2.8 on 2021-11-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20211101_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsimage',
            old_name='image',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='new',
            name='images',
        ),
        migrations.AddField(
            model_name='new',
            name='img',
            field=models.ManyToManyField(related_name='image', to='about.NewsImage'),
        ),
    ]
