# Generated by Django 3.2.8 on 2021-11-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20211101_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsimage',
            old_name='img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='new',
            name='img',
        ),
        migrations.AddField(
            model_name='new',
            name='images',
            field=models.ManyToManyField(related_name='news', to='about.NewsImage'),
        ),
    ]
