# Generated by Django 3.2.8 on 2021-11-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_rename_new_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
