# Generated by Django 3.2.8 on 2021-12-13 20:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(default=None, upload_to='about/')),
            ],
            options={
                'verbose_name': 'Haqqımızda',
                'verbose_name_plural': 'Haqqımızda',
            },
        ),
        migrations.CreateModel(
            name='Admissionrules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('total_rules', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('from_9_rules', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('from_11_rules', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'qəbul qaydaları',
                'verbose_name_plural': 'qəbul qaydaları',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='Max 30 char.', max_length=30, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title')),
                ('title_az', models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='Max 30 char.', max_length=30, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title')),
                ('title_az', models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(default=None, upload_to='faculty/')),
            ],
            options={
                'verbose_name': 'FBK',
                'verbose_name_plural': 'FBK',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='Max 30 char.', max_length=30, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title')),
                ('title_az', models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('image_icon', models.ImageField(default=None, upload_to='specialty/')),
                ('faculty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='specialty_faculty', to='about.faculty')),
            ],
            options={
                'verbose_name': 'Ixtisas',
                'verbose_name_plural': 'Ixtisaslar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='Max 30 char.', max_length=30, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title')),
                ('title_az', models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(default=None, upload_to='news/')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='news_category', to='about.category')),
            ],
            options={
                'verbose_name': 'Xəbərlər',
                'verbose_name_plural': 'Xəbərlər',
            },
        ),
    ]
