# Generated by Django 3.2.8 on 2021-12-14 09:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='Max 30 char.', max_length=30, verbose_name='Title')),
                ('title_en', models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title')),
                ('title_az', models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(help_text='Max 30 char.', max_length=30, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('description_az', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(default=None, upload_to='event/', verbose_name='Image')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'FBK', 'verbose_name_plural': 'FBKlar'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Xəbər', 'verbose_name_plural': 'Xəbərlər'},
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(default=None, upload_to='about/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(default=None, upload_to='faculty/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='news_category', to='about.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default=None, upload_to='news/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='faculty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='specialty_faculty', to='about.faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='image_icon',
            field=models.ImageField(default=None, upload_to='specialty/', verbose_name='Image'),
        ),
    ]
