# Generated by Django 3.2.8 on 2021-12-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Max 50 char.', max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_az',
            field=models.CharField(help_text='Max 50 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(help_text='Max 50 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_ru',
            field=models.CharField(help_text='Max 50 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Max 50 char.', max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_az',
            field=models.CharField(help_text='Max 50 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=models.CharField(help_text='Max 50 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_ru',
            field=models.CharField(help_text='Max 50 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='title',
            field=models.CharField(help_text='Max 50 char.', max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='title_az',
            field=models.CharField(help_text='Max 50 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='title_en',
            field=models.CharField(help_text='Max 50 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='title_ru',
            field=models.CharField(help_text='Max 50 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(help_text='Max 50 char.', max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Max 50 char.', max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_az',
            field=models.CharField(help_text='Max 50 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(help_text='Max 50 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(help_text='Max 50 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='practic',
            name='title',
            field=models.CharField(help_text='Max 50 char.', max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='practicplace',
            name='title',
            field=models.CharField(help_text='Max 50 char.', max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='title',
            field=models.CharField(help_text='Max 50 char.', max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='title_az',
            field=models.CharField(help_text='Max 50 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='title_en',
            field=models.CharField(help_text='Max 50 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='title_ru',
            field=models.CharField(help_text='Max 50 char.', max_length=30, null=True, verbose_name='Title'),
        ),
    ]
