# Generated by Django 3.2.8 on 2021-12-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_az',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_en',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_ru',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
