# Generated by Django 3.2.8 on 2021-12-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20211223_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Max 100 char.', max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_az',
            field=models.CharField(help_text='Max 100 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=models.CharField(help_text='Max 100 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_ru',
            field=models.CharField(help_text='Max 100 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Max 100 char.', max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_az',
            field=models.CharField(help_text='Max 100 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(help_text='Max 100 char.', max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(help_text='Max 100 char.', max_length=30, null=True, verbose_name='Title'),
        ),
    ]
