# Generated by Django 3.2.8 on 2021-12-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20211214_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_az',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_ru',
        ),
    ]
