# Generated by Django 3.2.8 on 2021-12-14 18:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dateofcreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Yaradilma tarixi',
                'verbose_name_plural': 'Yaradilma tarixi',
            },
        ),
    ]
