# Generated by Django 3.2.8 on 2021-12-21 15:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_dateofcreate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'karyera dəstəyi',
                'verbose_name_plural': 'karyera dəstəyi',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(help_text='Max 30 char.', max_length=30, verbose_name='Title')),
                ('image', models.ImageField(default=None, upload_to='gallery/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Practic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='Max 30 char.', max_length=30, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('image_icon', models.ImageField(default=None, upload_to='practic/', verbose_name='Image icon')),
                ('image', models.ImageField(default=None, upload_to='practic/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Practic',
                'verbose_name_plural': 'Practies',
            },
        ),
        migrations.CreateModel(
            name='PracticPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(help_text='Max 30 char.', max_length=30, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('practic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='practic_place', to='about.practic', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'PracticPlace',
                'verbose_name_plural': 'PracticPlaces',
            },
        ),
    ]
