# Generated by Django 3.2.8 on 2021-12-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_careersupport_gallery_practic_practicplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='DateTime'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
